name: shell crontab hello word

on:
  schedule:
    - cron:  '0 0 * * *'
    # - cron:  '*/10 * * * *'
  # 添加参数 允许手动执行此程序
  workflow_dispatch:
  
jobs:
  echo_hello_word:
    runs-on: ubuntu-latest
    name: My first Cron job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: echo=hello=word
        run: echo "hello word shell"
      # 设置北京当前时间
      - name: Get beijing file current date
        id: beijingfiledate
        run: |
          echo "::set-output name=utcDate::$(date  +'%Y/%m/%d %H:%M:%S')"
          echo "::set-output name=bjDate::$(date -d '+8 hour' +'%Y/%m/%d %H:%M:%S')"
      # 设置北京当前时间
      - name: show date
        run: |
          echo ${{ steps.beijingfiledate.outputs.utcDate }}
          echo ${{ steps.beijingfiledate.outputs.bjDate }}
